### ISSUE TITLE
Use the official API method for disabling settings

### ISSUE THREAD

**Issue by jjspace** [deathau/cm-show-whitespace-obsidian#13]
Back when I added settings for specific whitespace characters there was not an official way to disable settings so I used this [css hack](https://github.com/deathau/cm-show-whitespace-obsidian/blob/c4bb19a45a47e210c6c522a636f21f760225d036/styles.scss#L4) and created a request on their API github https://github.com/obsidianmd/obsidian-api/issues/8

```css
  .plugin-cm-show-whitespace-disabled {
    opacity: 0.6;

    .checkbox-container {
      cursor: not-allowed;
      // this is *not* an adequate way to disable an input but it's all we can do right now
      pointer-events: none;
    }
  }
```

There is now an [official way](https://github.com/obsidianmd/obsidian-api/issues/8#issuecomment-784505551) in the API to disable a setting using `setDisabled` on both Setting and Component level. [This section](https://github.com/deathau/cm-show-whitespace-obsidian/blob/c4bb19a45a47e210c6c522a636f21f760225d036/main.ts#L141) should be updated to use the new method.
